driver_sally();
chassis_2017();
power_plant_2017();
suspension_front_2017();
suspension_rear_2017();
wheel_front_2017();
wheel_rear_2017();


FSAE_Race_Car = struct(...
    'team',             'Texas A&M',...
    'year',             2017,...
    'top_speed',        80,...
    't2top_speed',      t2top_speed(3,80),...
    'pilot',            pilot,...
    'chassis',          chassis,...
    'power_plant',      power_plant,...
    'suspension_front', suspension_front,...
    'suspension_rear',  suspension_rear,...
    'wheel_front',      wheel_front,...
    'wheel_rear',       wheel_rear);