
function [FSAE_Race_Car] = car_2017()

    FSAE_Race_Car = struct(...
        'team','Texas A&M',...
        'year',2017,...
        'top_speed',80,...
        't2top_speed',t2top_speed(3,80),...
        'pilot',driver_sally(),...
        'chassis',chassis_2017(),...
        'power_plant',power_plant_2017(),...
        'suspension_front',suspension_front_2017(),...
        'suspension_rear',suspension_rear_2017(),...
        'wheel_front',wheel_front_2017(),...
        'wheel_rear',wheel_rear_2017());