function [FSAE_Race_Car] = car_2016()
    FSAE_Race_Car = struct(...
        'team','Texas A&M',...
        'year',2016,...
        'top_speed',175,...
        't2top_speed',t2top_speed(2.1,175),...
        'pilot',driver_tom(),...
        'chassis',chassis_2016(),...
        'power_plant',power_plant_2016(),...
        'suspension_front',suspension_front_2016(),...
        'suspension_rear',suspension_rear_2016(),...
        'wheel_front',wheel_front_2016(),...
        'wheel_rear',wheel_rear_2016());

