function [suspension_rear] = suspension_rear_2014()
    suspension_rear = struct(...
        'model','Öhlins TTX25',...
        'location','inboard',...
        'angle',0,...
        'travel',55*0.0393701,...
        'k',250,...
        'c',17);