function [suspension_front] = suspension_front_2014()
    suspension_front = struct(...
        'model','Öhlins TTX25',...
        'location','inboard',...
        'angle',0,...
        'travel',55*0.0393701,...
        'k',225,...
        'c',5);