function [suspension_front] = suspension_front_2017()
suspension_front = struct(...
    'model','Öhlins TTX25 MKII',...
    'location','outboard',...
    'angle',44,...
    'travel',2,...
    'k',350,...
    'c',5);