function [suspension_rear] = suspension_rear_2016()
suspension_rear = struct(...
    'model','Öhlins TTX25 MKII',...
    'location','inboard',...
    'angle',0,...
    'travel',2,...
    'k',300,...
    'c',12.5);