chassis = struct(...
    'team',         'Aggie',...
    'year',         2016,...
    'weight',       219,...
    'length',       92.35,...
    'diameter',     42,...
    'wheelbase',    60.25,...
    'radius_f',     24.5,...
    'radius_r',     24,...
    'cg_X',         39.9,...
    'cg_Z',         10.49,...
    'seat_X',       34.5,...
    'seat_Z',       2.25,...
    'motor_X',      36.9,...
    'motor_Z',      11.91);