clc; clear all; close all;

%% 2014
car_2014
fprintf('============================ 2014 ==============================\n')
fprintf('The leverage ratio for the Aggie 2014 front of the car is\n')
disp(get_leverage_ratio('front',FSAE_Race_Car))
fprintf('and the leverage ratio fo rthe Aggie 2014 rear of the car is\n')
disp(get_leverage_ratio('rear',FSAE_Race_Car))
fprintf('--------------------------- 1 DOF ------------------------------\n')
fprintf('The mass matrix [slugs] for the Aggie 2014 car for 1 DOF is\n')
disp(get_mass_matrix('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('The stiffness matrix [lb/ft] for the Aggie 2014 car for 1 DOF is\n')
fprintf('  %4.1f\n\n',get_stiffness_matrix('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('The damping matrix [lb/(ft/sec)] for the Aggie 2014 car for 1 DOF is\n')
disp(get_damping_matrix('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('The static deflection [ft] for the Aggie 2014 car for 1 DOF is\n')
disp(get_static_deflection('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('--------------------------- 2 DOF ------------------------------\n')
fprintf('The mass matrix [slugs] for the Aggie 2014 car for 1 DOF is\n')
disp(get_mass_matrix('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('The stiffness matrix [lb/ft] for the Aggie 2014 car for 1 DOF is\n')
disp(get_stiffness_matrix('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('The damping matrix [lb/(ft/sec)] for the Aggie 2014 car for 1 DOF is\n')
disp(get_damping_matrix('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('The static deflection [ft] for the Aggie 2014 car for 1 DOF is\n')
disp(get_static_deflection('quarter_car_2_DOF',FSAE_Race_Car))

%% 2016
car_2016
fprintf('\n\n============================ 2016 ==============================\n')
fprintf('The leverage ratio for the Aggie 2016 front of the car is\n')
disp(get_leverage_ratio('front',FSAE_Race_Car))
fprintf('and the leverage ratio fo rthe Aggie 2016 rear of the car is\n')
disp(get_leverage_ratio('rear',FSAE_Race_Car))
fprintf('--------------------------- 1 DOF ------------------------------\n')
fprintf('The mass matrix [slugs] for the Aggie 2016 car for 1 DOF is\n')
disp(get_mass_matrix('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('The stiffness matrix [lb/ft] for the Aggie 2016 car for 1 DOF is\n')
fprintf('  %4.1f\n\n',get_stiffness_matrix('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('The damping matrix [lb/(ft/sec)] for the Aggie 2016 car for 1 DOF is\n')
disp(get_damping_matrix('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('The static deflection [ft] for the Aggie 2016 car for 1 DOF is\n')
disp(get_static_deflection('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('--------------------------- 2 DOF ------------------------------\n')
fprintf('The mass matrix [slugs] for the Aggie 2016 car for 1 DOF is\n')
disp(get_mass_matrix('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('The stiffness matrix [lb/ft] for the Aggie 2016 car for 1 DOF is\n')
disp(get_stiffness_matrix('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('The damping matrix [lb/(ft/sec)] for the Aggie 2016 car for 1 DOF is\n')
disp(get_damping_matrix('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('The static deflection [ft] for the Aggie 2016 car for 1 DOF is\n')
disp(get_static_deflection('quarter_car_2_DOF',FSAE_Race_Car))

%% 2017
car_2017
fprintf('\n\n============================ 2017 ==============================\n')
fprintf('The leverage ratio for the Aggie 2017 front of the car is\n')
disp(get_leverage_ratio('front',FSAE_Race_Car))
fprintf('and the leverage ratio fo rthe Aggie 2017 rear of the car is\n')
disp(get_leverage_ratio('rear',FSAE_Race_Car))
fprintf('--------------------------- 1 DOF ------------------------------\n')
fprintf('The mass matrix [slugs] for the Aggie 2017 car for 1 DOF is\n')
disp(get_mass_matrix('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('The stiffness matrix [lb/ft] for the Aggie 2017 car for 1 DOF is\n')
fprintf('  %4.1f\n\n',get_stiffness_matrix('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('The damping matrix [lb/(ft/sec)] for the Aggie 2017 car for 1 DOF is\n')
disp(get_damping_matrix('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('The static deflection [ft] for the Aggie 2017 car for 1 DOF is\n')
disp(get_static_deflection('quarter_car_1_DOF',FSAE_Race_Car))
fprintf('--------------------------- 2 DOF ------------------------------\n')
fprintf('The mass matrix [slugs] for the Aggie 2017 car for 1 DOF is\n')
disp(get_mass_matrix('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('The stiffness matrix [lb/ft] for the Aggie 2017 car for 1 DOF is\n')
disp(get_stiffness_matrix('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('The damping matrix [lb/(ft/sec)] for the Aggie 2017 car for 1 DOF is\n')
disp(get_damping_matrix('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('The static deflection [ft] for the Aggie 2017 car for 1 DOF is\n')
disp(get_static_deflection('quarter_car_2_DOF',FSAE_Race_Car))
fprintf('\n\n\n\n')