wheel_front = struct(...
    'model',        'Hoosier 18x7.5-10 R25B',...
    'weight',       23,...
    'travel',       2,...
    'deflection',   2,...
    'k',            540,...
    'c',            3);