driver_harry();
chassis_2017();
motor_2014();

team_O_suspension_front();
team_O_suspension_rear();
team_O_wheel_front();
team_O_wheel_rear();


FSAE_Race_Car = struct(...
    'team',             'Team O',...
    'year',             2017,...
    'top_speed',        62,...
    't2top_speed',      3.841652151016275,...
    'pilot',            pilot,...
    'chassis',          chassis,...
    'power_plant',      power_plant,...
    'suspension_front', suspension_front,...
    'suspension_rear',  suspension_rear,...
    'wheel_front',      wheel_front,...
    'wheel_rear',       wheel_rear);